---
- name: Creates backend directory
  file:
    path: ~/backend/
    state: directory

- name: Copy and unarchive artifact
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend/

# not really needed since the infrastructure is created each time
- name: Stop Previous PM2
  command: pm2 delete default
  ignore_errors: yes

- name: Start PM2
  command: |
    cd ~/backend/dist
    pm2 start main.js
